/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Student
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cnpLabel = new javax.swing.JLabel();
        cnpTextField = new javax.swing.JTextField();
        cnpCheckButton = new javax.swing.JButton();
        ansTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CNP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 102, 0))); // NOI18N

        cnpLabel.setForeground(new java.awt.Color(204, 0, 204));
        cnpLabel.setText("CNP:");

        cnpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpTextFieldActionPerformed(evt);
            }
        });

        cnpCheckButton.setForeground(new java.awt.Color(51, 51, 255));
        cnpCheckButton.setText("Check");
        cnpCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpCheckButtonActionPerformed(evt);
            }
        });

        ansTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cnpCheckButton)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cnpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ansTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(cnpTextField))))
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpLabel)
                    .addComponent(cnpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cnpCheckButton)
                .addGap(18, 18, 18)
                .addComponent(ansTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpTextFieldActionPerformed

    private boolean cnpControlDigit(String cnp)
    {
        String checkDigitNumber = "279146358279";
        int cnpCheckDigit = Character.getNumericValue(cnp.charAt(cnp.length() - 1));
        long sum = 0;
        
        for (int i = 0; i < cnp.length() - 1; ++i) {
            sum += Character.getNumericValue(cnp.charAt(i)) * Character.getNumericValue(checkDigitNumber.charAt(i));
        }

        long remainder = sum % 11;
        if (remainder == 10) {
            if (cnpCheckDigit != 1)
                return false;
        }
        else if (cnpCheckDigit != remainder)
            return false;
 
        return true;
    }
    
    private void showAnswer(boolean ans, String text)
    {
        if (ans)
            ansTextField.setText(text);
        else
            ansTextField.setText(text);
    }

    private void cnpCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpCheckButtonActionPerformed
        // TODO add your handling code here:
        String cnp = cnpTextField.getText();

        if (cnp.length() != 13) {
            showAnswer(false, "Invalid cnp size");
            return;
        }

        int sexDigit = cnp.charAt(0);
        if (sexDigit != '1' && sexDigit != '2' && sexDigit < '5') {
           showAnswer(false, "Invalid sex digit");
           return;
        }

        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        int lastTwoYearDigits = currentYear % 100;
        int cnpYear = Integer.parseInt(cnp.substring(1, 3));
        if (cnpYear < lastTwoYearDigits)
            cnpYear += 2000;
        else
            cnpYear += 1900;

        int month = Integer.parseInt(cnp.substring(3, 5));
        if (month == 0 || month > 12) {
            showAnswer(false, "Invalid month");
            return;
        }

        int day = Integer.parseInt(cnp.substring(5, 7));
        int daysInMonth = new GregorianCalendar(cnpYear, month - 1, 1).getActualMaximum(Calendar.DAY_OF_MONTH);
        if (day == 0 || day > daysInMonth) {
            showAnswer(false, "Invalid day");
            return;
        }

        int county = Integer.parseInt(cnp.substring(7, 9));
        if (county == 0 || county > 52) {
            showAnswer(false, "Invalid county");
            return;
        }

        int num = Integer.parseInt(cnp.substring(9, 12));
        if (num == 0) {
            showAnswer(false, "Invalid given number");
            return;
        }

        if (!cnpControlDigit(cnp)) {
           showAnswer(false, "Invalid check digit");
           return;
        }

        showAnswer(true, "OK");
    }//GEN-LAST:event_cnpCheckButtonActionPerformed

    private void ansTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ansTextField;
    private javax.swing.JButton cnpCheckButton;
    private javax.swing.JLabel cnpLabel;
    private javax.swing.JTextField cnpTextField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
